version: '3'
services:
  redis:
     image: 'redis:5.0-alpine'
     command: redis-server --appendonly yes
     restart: unless-stopped
     ports:
          - 127.0.0.1:6379:6379
     volumes:
       - redismount:/data
     sysctls:
       net.core.somaxconn: '2048'
volumes:
    redismount: